name: Lint, Scan and build

on: push

jobs:
  build:
    name: Lint and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm install --legacy-peer-deps
      - run: npm run lint
      - run: npm run build
