# name: Lint, Scan and build 

# on: push

# jobs:

#   build:
#     name: Lint and Build
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14]

#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js 12.20
#       uses: actions/setup-node@v2
#       with:
#        node-version: '14'
#     - run: npm install 
#     - run: npm run lint
#     - run: | 
#           npm run build
#           echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > .npmrc
#           echo "@trufla:registry=https://npm.pkg.github.com" >> .npmrc
#           npm run publish


